export const ActionTypes = {
  // FETCH_ALL_PRODUCTS: "FETCH_ALL_PRODUCTS",
  SET_ALL_PRODUCTS: "SET_ALL_PRODUCTS",

  //Filter actions
  SORT: "SORT",
  FAST_DELIVERY: "FAST_DELIVERY",
  EXCLUDE_OUT_OF_STOCK: "EXCLUDE_OUT_OF_STOCK",
  RATING: "RATING",
  RESET: "RESET",
  // FETCH_SINGLE_PRODUCT: "FETCH_SINGLE_PRODUCT",

  //Cart actions
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
};
