export const ActionTypes = {
  // FETCH_ALL_PRODUCTS: "FETCH_ALL_PRODUCTS",
  SET_ALL_PRODUCTS: "SET_ALL_PRODUCTS",
  SORT_BY_ASC: "SORT_BY_ASC",
  SORT_BY_DESC: "SORT_BY_DESC",
  // FETCH_SINGLE_PRODUCT: "FETCH_SINGLE_PRODUCT",

  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
}